
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'leftORleftANDleftNOTTK AND OR NOT LPAREN RPARENexpression : expression AND expression\n                  | expression OR expressionexpression : NOT expressionexpression : LPAREN expression RPARENexpression : TK'
    
_lr_action_items = {'NOT':([0,2,3,5,6,],[2,2,2,2,2,]),'LPAREN':([0,2,3,5,6,],[3,3,3,3,3,]),'TK':([0,2,3,5,6,],[4,4,4,4,4,]),'$end':([1,4,7,9,10,11,],[0,-5,-3,-1,-2,-4,]),'AND':([1,4,7,8,9,10,11,],[5,-5,-3,5,-1,5,-4,]),'OR':([1,4,7,8,9,10,11,],[6,-5,-3,6,-1,-2,-4,]),'RPAREN':([4,7,8,9,10,11,],[-5,-3,11,-1,-2,-4,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'expression':([0,2,3,5,6,],[1,7,8,9,10,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> expression","S'",1,None,None,None),
  ('expression -> expression AND expression','expression',3,'p_expression_binop','bool_lex_parse.py',52),
  ('expression -> expression OR expression','expression',3,'p_expression_binop','bool_lex_parse.py',53),
  ('expression -> NOT expression','expression',2,'p_expression_not','bool_lex_parse.py',58),
  ('expression -> LPAREN expression RPAREN','expression',3,'p_expression_group','bool_lex_parse.py',62),
  ('expression -> TK','expression',1,'p_expression_token','bool_lex_parse.py',66),
]
